export const GET_TOP_STORIES_REQUEST = 'GET_TOP_STORIES_REQUEST';
export const GET_TOP_STORIES_SUCCESS = 'GET_TOP_STORIES_SUCCESS';
export const GET_TOP_STORIES_FAILURE = 'GET_TOP_STORIES_FAILURE';

export const SELECT_STORIES = 'SELECT_STORIES';

export const GET_STORIES_CONTENT_REQUEST = 'GET_STORIES_CONTENT_REQUEST';
export const GET_STORIES_CONTENT_SUCCESS = 'GET_STORIES_CONTENT_SUCCESS';
export const GET_STORIES_CONTENT_FAILURE = 'GET_STORIES_CONTENT_FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const GET_RANDOM_STORIES_REQUEST = 'GET_RANDOM_STORIES_REQUEST';
export const GET_RANDOM_STORIES_SUCCESS = 'GET_RANDOM_STORIES_SUCCESS';
